### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by blackboxlogic** [lincolnkamenides/COS470#3]
Looks like you need to `add test cases`
https://github.com/lincolnkamenides/COS470/blob/da835707a193d7ef8645556b2cc2f9eeaec1ccc0/COS%20470/Assignment3/Assignment3.Test/UnitTest1.cs#L13

Can't find anything else to complain about.

**Comment by lincolnkamenides** [comment]
I added a few test cases for each method.
https://github.com/lincolnkamenides/COS470/blob/97456b100f2bee5206906fcd87ac5c3a29117de8/COS%20470/Assignment3/Assignment3.Tests/UnitTestLocationData.cs#L11

**Comment by blackboxlogic** [comment]
There's not enough here to grade.
The csproj files for your tests and API are missing. I'd like to be able to run your unit tests and you API. The solution won't load and I can't find any evidence that you called your API using postman (was hoping for a screenshot).

**Comment by lincolnkamenides** [comment]
I added the csproj files so the tests and API should be there. @blackboxlogic

**Comment by blackboxlogic** [comment]
The assignment specifies to provide evidence of the output from calling your API. This is so that I have _something_ to grade in case your program doesn't compile, which it doesn't (as it is in git).
To get a grade, post screen shots of you calling your API from postman and screenshots of your unit tests passing.

**Comment by lincolnkamenides** [comment]
I added screenshots to the Assignment 3 folder and below as well. @blackboxlogic 

**API**
![API Pic](https://user-images.githubusercontent.com/46967860/71597962-2ac2bd80-2b13-11ea-9c30-1214cb36d08b.PNG)

**UNIT TESTS**
![Test Pic](https://user-images.githubusercontent.com/46967860/71597940-1e3e6500-2b13-11ea-9962-775c75d46b8f.png)

**Comment by blackboxlogic** [comment]
Oh good! I'll update your grade in a minute.

**Comment by blackboxlogic** [comment]
100/100
And after a LOT of fiddling I got it to work on my computer!
![image](https://user-images.githubusercontent.com/31355456/71598537-344d2500-2b15-11ea-87d4-3f9151e11d8e.png)
